vim.g.R_disable_cmds = {
  -- "RStart",
  "RCustomStart",
  -- "RClose",
  "RSaveClose",
  "RClearAll",
  "RClearConsole",
  "RSimpleComment",
  "RSimpleUnComment",
  "RToggleComment",
  "RRightComment",
  "RIndent",
  -- "RNextRChunk",
  -- "RPreviousRChunk",
  -- "RSendLine",
  -- "RDSendLine",
  "RSendLAndOpenNewOne",
  "RNLeftPart",
  "RNRightPart",
  "RILeftPart",
  "RIRightPart",
  "RDSendLineAndInsertOutput",
  "RSendAboveLines",
  -- "RSendSelection",
  "RESendSelection",
  "RDSendSelection",
  "REDSendSelection",
  "RSendMotion",
  "RSendSelAndInsertOutput",
  "RSendMBlock",
  "RESendMBlock",
  "RDSendMBlock",
  "REDSendMBlock",
  "RSendParagraph",
  "RESendParagraph",
  "RDSendParagraph",
  "REDSendParagraph",
  "RSendFunction",
  "RESendFunction",
  "RDSendFunction",
  "REDSendFunction",
  -- "RSendFile",
  -- "RHelp",
  -- "RPlot",
  -- "RSPlot",
  -- "RShowArgs",
  "RShowEx",
  "RShowRout",
  -- "RObjectNames",
  -- "RObjectPr",
  -- "RObjectStr",
  -- "RViewDF (view data.frame or other object)",
  "RViewDFs (view object in split window)",
  "RViewDFv (view object in vertically split window)",
  "RViewDFa (view object in split window above the current one)",
  "RDputObj",
  "RSetwd",
  -- "RSummary",
  "RListSpace",
  "RSendChunk",
  "RDSendChunk",
  -- "RESendChunk",
  -- "REDSendChunk",
  "RSendChunkFH (from the first chunk to here)",
  "RBibTeX (Sweave)",
  "RBibTeXK (Knitr)",
  "RSweave",
  "RKnit",
  "RMakeHTML",
  "RMakePDF (Sweave)",
  "RMakePDFK (Knitr)",
  "RMakePDFKb (.Rmd, beamer)",
  "RMakeODT (.Rmd, Open document)",
  "RMakeWord (.Rmd, Word document)",
  "RMakeRmd (rmarkdown default)",
  "RMakeAll (rmarkdown all in YAML)",
  "ROpenPDF",
  "RSyncFor (SyncTeX search forward)",
  "RGoToTeX (Got to LaTeX output)",
  "RSpinFile",
  -- "RNextRChunk",
  -- "RPreviousRChunk",
  "RQuartoRender",
  "RQuartoPreview",
  "RQuartoStop",
  "ROpenRefFile",
  "RDebug",
  "RUndebug",
  -- "RUpdateObjBrowser",
  "ROpenLists",
  "RCloseLists",
}

vim.g.R_close_term = true
vim.g.R_esc_term = true
vim.g.R_min_editor_width = 80
vim.g.R_rconsole_width = 1000
vim.g.R_rconsole_height = math.floor(vim.fn.winheight(0) / 3)
vim.g.R_after_start = {
  ":winc j",
  ":vsplit",
  ":vertical resize " .. math.floor(vim.fn.winwidth(0) / 3),
  ":winc k",
}
vim.g.R_objbr_place = "script,right"
vim.g.R_objbr_w = math.floor(vim.fn.winwidth(0) / 4)
vim.g.R_objbr_opendf = 0
vim.g.R_assign = 0
vim.g.R_rmdchunk = 0
-- vim.g.R_csv_delim = ","
vim.g.R_csv_app = "open-with-excel"
vim.g.R_nvimpager = "tab" -- show docs in new tab
vim.g.R_path = "C:\\Program Files\\R\\R-4.3.2\\bin\\x64"
